### ISSUE TITLE
[Embedded NodeJS] Debugging

### ISSUE THREAD

**Issue by pcan** [continuationlabs/blog-examples#1]
Hi, is there a way to debug javascript code running in the embedded NodeJS example?

**Comment by cjihrig** [comment]
Do the normal Node debug/inspect command line flags work?

**Comment by pcan** [comment]
Oh, sorry, I had a look at the `main` code just now and I didn't noticed before that you pass `argc` and `argv`: to the constructor `node::Start(argc, argv);` so it should work, I'll give a try ASAP. Thank you.

**Comment by cjihrig** [comment]
Did it work?

**Comment by pcan** [comment]
I tried to build your example, but I get the following linker error:
```
embed.cc:(.text+0x26): undefined reference to `node::Start(int, char**)'
collect2: error: ld returned 1 exit status
```
I'm using Ubuntu 16.04, with everything up to date. The only strange thing I get is the library name: `libnode.so.51`. I did some search and I found [this](http://www.sisik.eu/blog/build-node-js-for-android): I also tried the `soname` param renaming as suggested in this page, but I get the same error.

**Comment by cjihrig** [comment]
Did you build the Node shared library yourself on Ubuntu? If not, you'll have to do that. If you're using anything other than macOS, you may have to deviate from the tutorial a bit.

**Comment by pcan** [comment]
Yes, I built node as shared library from sources (v.7.9.0). It seems the compiler output does not espose the node::Start function. Maybe I have to tweak other compilation settings?

**Comment by pcan** [comment]
Ok, now it works. I found 2 different issues:
- the library option for the g++ command should be passed in reverse dependency order. Instead of `g++ -std=c++11 -L. -lnode -I./node-v7.9.0/include/node embed.cc -o embed` it worked with `g++ -std=c++11 -L.  -I./node-v7.9.0/include/node embed.cc -o embed -lnode`.
- then, I got `error while loading shared libraries: libnode.so`, so I added ` -Wl,-rpath,'$ORIGIN'` and it worked just fine.

This is the working one (I had to remove the .so version from the file name, but it's just a detail):
`g++ -std=c++11 -Wl,-rpath,'$ORIGIN' -L.  -I./node-v7.9.0/include/node embed.cc -o embed -lnode`

**Comment by cjihrig** [comment]
I'm glad you got it sorted out. Does that mean this issue can be closed?
